name: Build

on:
  push:
    branches:
      - master
      - workflows-testing
  pull_request:
    branches:
      - master
      - devmaster

jobs:
  build_debug:
    runs-on: windows-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: make build dir
      run: mkdir build_debug
    - name: run cmake
      run: cmake ../ -G "Visual Studio 16 2019" -A x64 -DRW3DM_BUILD_ON2JSON=OFF -DRW3DM_BUILD_JSON2ON=OFF -DRW3DM_BUILD_ON_DLL=ON
      working-directory: ./build_debug
    - name: make
      run: cmake --build . --config Debug --target opennurbs
      working-directory: ./build_debug
    - name: make install
      run: cmake --build . --config Debug --target install
      working-directory: ./build_debug
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: opennurbs_dbg
        path: ./build_debug/install

  build_release:
    runs-on: windows-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: make build dir
      run: mkdir build_release
    - name: run cmake
      run: cmake ../ -G "Visual Studio 16 2019" -A x64 -DRW3DM_BUILD_ON2JSON=OFF -DRW3DM_BUILD_JSON2ON=OFF -DRW3DM_BUILD_ON_DLL=ON
      working-directory: ./build_release
    - name: make
      run: cmake --build . --config Release --target opennurbs
      working-directory: ./build_release
    - name: make install
      run: cmake --build . --config Release --target install
      working-directory: ./build_release
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: opennurbs
        path: ./build_release/install
